Fkl\FranklinBundle\Entity\CategorieIntervention:
    type: entity
    table: categorie_intervention
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO         
    fields:
        nom:
            type: string
            length: 255
    oneToMany:
        interventions:
            targetEntity: Intervention
            mappedBy: categorieintervention
    lifecycleCallbacks: {  }
