Fkl\FranklinBundle\Entity\Image:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
              
    fields:
        filename:
            type:         string
            length:       100
            nullable : true         
        updated:       
            type:         string
            nullable:     true
            
    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]    
            
    manyToOne:
        produit:
            
            targetEntity: Produit
            inversedBy: images
            joinColumn:
              name: produit_id
              referencedColumnName: id 
