Fkl\FranklinBundle\Entity\Intervention:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO         
    lifecycleCallbacks: {  }
    fields:
        titre:
            type: string
            length: 255
        date:
            type: date
        tarif:
            type: decimal
        adresse:
            type: string
            lenght: 255
        cp:
            type: integer
            lenght: 5
        ville:
            type: string
            lenght: 255
            
    manyToOne:
        user:
            targetEntity: Fkl\UserBundle\Entity\User
            joinColumn:
              name: user_id
              referencedColumnName: id