homepage:
    pattern:  /
    defaults: { _controller: FklFranklinBundle:Home:index }
installationpage:
    pattern:  /installations
    defaults: { _controller: FklFranklinBundle:Installation:index }
produitpage:
    pattern:  /produits
    defaults: { _controller: FklFranklinBundle:Produit:index }
produitpagefull:
    pattern:  /produits/full
    defaults: { _controller: FklFranklinBundle:Produit:full }
contactpage:
    pattern:  /contact
    defaults: { _controller: FklFranklinBundle:Contact:index }
admin:
    pattern:  /admin
    defaults: { _controller: FklFranklinBundle:Admin:index }

#FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
FklFranklinBundle_admin_category:
        resource: "@FklFranklinBundle/Resources/config/routing/category.yml"
        prefix:   /admin/category

FklFranklinBundle_admin_image:
        resource: "@FklFranklinBundle/Resources/config/routing/image.yml"
        prefix:   /admin/image

FklFranklinBundle_admin_product:
        resource: "@FklFranklinBundle/Resources/config/routing/product.yml"
        prefix:   /admin/product
        
FklFranklinBundle_api_product:
        resource: "@FklFranklinBundle/Resources/config/routing/product_api.yml"
        prefix:   /api/product

FklFranklinBundle_admin_intervention_category:
        resource: "@FklFranklinBundle/Resources/config/routing/interventioncategory.yml"
        prefix:   /admin/intervention/category

FklFranklinBundle_admin_intervention:
        resource: "@FklFranklinBundle/Resources/config/routing/intervention.yml"
        prefix:   /admin/intervention