<?php

namespace Fkl\FranklinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionCategoryRepository extends EntityRepository
{
    
}
