admin_category_root:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin_category
        permanent: true
        
admin_category:
    pattern:  /list/{page}
    defaults: { _controller: "FklFranklinBundle:Category:index", page: 1 }
    requirements:
        page: .+

admin_category_show:
    pattern:  /{id}/show
    defaults: { _controller: "FklFranklinBundle:Category:show" }

admin_category_new:
    pattern:  /new
    defaults: { _controller: "FklFranklinBundle:Category:new" }

admin_category_create:
    pattern:  /create
    defaults: { _controller: "FklFranklinBundle:Category:create" }
    requirements: { _method: post }

admin_category_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FklFranklinBundle:Category:edit" }

admin_category_update:
    pattern:  /{id}/update
    defaults: { _controller: "FklFranklinBundle:Category:update" }
    requirements: { _method: post|put }

admin_category_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FklFranklinBundle:Category:delete" }
