admin_user_root:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin_user
        permanent: true
        
admin_user:
    pattern:  /list/{page}
    defaults: { _controller: "FklFranklinBundle:User:index", page: 1 }
    requirements:
        page: .+

admin_user_show:
    pattern:  /{id}/show
    defaults: { _controller: "FklFranklinBundle:User:show" }

admin_user_new:
    pattern:  /new
    defaults: { _controller: "FklFranklinBundle:User:new" }

admin_user_create:
    pattern:  /create
    defaults: { _controller: "FklFranklinBundle:User:create" }
    requirements: { _method: post }

admin_user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FklFranklinBundle:User:edit" }

admin_user_update:
    pattern:  /{id}/update
    defaults: { _controller: "FklFranklinBundle:User:update" }
    requirements: { _method: post|put }

admin_user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FklFranklinBundle:User:delete" }
